# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ebiznesBackendContainer

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_726f59de59ac4e2d838dcf71f4901b3e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d3713ae2da8c44bb8aada25b0f6893f3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_726f59de59ac4e2d838dcf71f4901b3e }}/robertochmanek/ebiznes_backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ebiznesBackendContainer'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_54f59c45c927490092141b60e331cf0f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_726f59de59ac4e2d838dcf71f4901b3e }}/robertochmanek/ebiznes_backend:${{ github.sha }}'